### PR TITLE
Major housekeeping

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
This pull request has the following changes

- [x] upgrade babel from 6 to 7
- [x] upgrade webpack from 2 to 4
- [x] add [editorconfig](https://editorconfig.org/) for maintaining code standards
- [x] update the coding style in the template, uses Vue's [recommended](https://vuejs.org/v2/style-guide/#Priority-C-Recommended) style
- [x] add `VueLoaderPlugin()` which is required in webpack 4 configuration
- [x] upgrade dev dependencies. uses all the latest technologies.

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
@phegman : Any comments / suggestions / thoughts?

**Comment by vinayakkulkarni** [comment]
Bump

**Comment by vinayakkulkarni** [comment]
🛎

**Comment by phegman** [comment]
Thanks! I'll try and take a look at this in the next week or so. I am (slowly) working on rewriting this plugin in TypeScript and streamlining the build/dev config. I may try and merge this in the meantime but need to do some testing on it first to make sure everything is still working as expected.

**Comment by vinayakkulkarni** [comment]
Do take a look @ https://soal.github.io/vue-mapbox/

Also this: https://github.com/soal/vue-mapbox/issues/111

**Comment by phegman** [comment]
Closing this out as I have released v2.0.*. I appreciate the help though! Feel free to open a PR for anything related to the recent v2.0.* release

**Pull request closed without merging**
